repos:
#  - repo: https://github.com/pre-commit/mirrors-isort
#    rev: v4.3.20
#    hooks:
#      - id: isort
#        language_version: python3.7
  - repo: https://github.com/python/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
        exclude: 'mibs'
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
      - id: flake8
#        additional_dependencies: [flake8-docstrings]
        language_version: python3.7
